apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config
  labels:
    {{- include "employee-management.labels" . | nindent 4 }}
data:
  ENVIRONMENT_NAME: {{ .Values.global.environment | quote }}
  PLATFORM_TEAM_EMAIL: {{ .Values.platformTeam.email | quote }}
  DEPLOYMENT_VERSION: {{ .Values.image.tag | default .Chart.AppVersion | quote }}

