global:
  environment: production

image:
  repository: employee-api-prod
  tag: "v1.0.0"

platformTeam:
  email: platform-ops@company.com

ingress:
  host: employee-api.host
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPU: 70
  targetMemory: 75

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 2000m
    memory: 2048Mi
    
