global:
  environment: production

image:
  repository: ://your-registry.com
  tag: "v1.0.0"

platformTeam:
  email: platform-ops@company.com

ingress:
  host: ://company.com
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPU: 70
  targetMemory: 75

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi
    
